### ISSUE TITLE
Where can I find the paper?

### ISSUE THREAD

**Issue by vanoracai** [CCChenhao997/DualGCN-ABSA#1]
Hi, thanks for your interesting work! I wish to take a look at the paper while cannot find it online. Would you mind sharing it with me?

**Comment by CCChenhao997** [comment]
Sorry for my late reply, I have added a link to the paper in README.

**Comment by CCChenhao997** [comment]
> Hi, thanks for your interesting work! I wish to take a look at the paper while cannot find it online. Would you mind sharing it with me?

Sorry for my late reply, I have added a link to the paper in README.
