### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by kezeming** [CCChenhao997/DualGCN-ABSA#13]
Hello！
I have a question about the dataset

The paper is constructed using LAL-parse, such as this sentence "I charge it at night and skip taking the cord with me because of the good battery life.".

Why do I construct 'head' and 'Deprel' differently? And what's the meaning of "head"?

**Comment by CCChenhao997** [comment]
This [blog](https://towardsdatascience.com/natural-language-processing-dependency-parsing-cf094bbbe3f7) may help you.

**Comment by CCChenhao997** [comment]
> Hello！ I have a question about the dataset
> 
> The paper is constructed using LAL-parse, such as this sentence "I charge it at night and skip taking the cord with me because of the good battery life.".
> 
> Why do I construct 'head' and 'Deprel' differently? And what's the meaning of "head"?

This [blog](https://towardsdatascience.com/natural-language-processing-dependency-parsing-cf094bbbe3f7) may help you.
