### ISSUE TITLE
OSError for  'xlnet-large-cased' 

### ISSUE THREAD

**Issue by fang-kun** [CCChenhao997/DualGCN-ABSA#21]
I follow all your README.md steps, but DualGCN can not run. Could you tell me why? I use GTX1660TI with python3.6.8.

OSError: Can't load weights for 'xlnet-large-cased'. Make sure that:

- 'xlnet-large-cased' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'xlnet-large-cased' is the correct path to a directory containing a file named one of pytorch_model.bin, tf_model.h5, model.ckpt.

**Comment by ryujin66** [comment]
I meet this error too, do you fine a way to solve it?

**Comment by fang-kun** [comment]
> I meet this error too, do you fine a way to solve it?

Yes, but I have new problem now. Anyway, I can help you fix it first. Please email me with kkkr8s@foxmail.com
